package seed

import (
	"ekapterka/internal/models"
)

func strPtr(s string) *string {
	return &s
}

var Categories = []models.Category{
	// ===== Снаряжение =====
	{
		ID:       "equipment",
		Title:    "Снаряжение",
		ParentID: strPtr(models.RootParentID),
		Path:     []string{"equipment"},
		Level:    0,
		Order:    10,
		IsLeaf:   false,
	},

	// --- Горное ---
	{
		ID:       "mountain",
		Title:    "Горное",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "mountain"},
		Level:    1,
		Order:    10,
		IsLeaf:   false,
	},

	{
		ID:       "hardware",
		Title:    "Железо",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "hardware"},
		Level:    2,
		Order:    10,
		IsLeaf:   false,
	},
	{
		ID:       "carabiners",
		Title:    "Карабины",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "carabiners"},
		Level:    3,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "figure_eights",
		Title:    "Восьмерки",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "figure_eights"},
		Level:    3,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "ascenders",
		Title:    "Жумары",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "ascenders"},
		Level:    3,
		Order:    30,
		IsLeaf:   true,
	},
	{
		ID:       "hardware_other",
		Title:    "Другое",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "hardware_other"},
		Level:    3,
		Order:    40,
		IsLeaf:   true,
	},

	{
		ID:       "ropes",
		Title:    "Веревки",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "ropes"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "crampons",
		Title:    "Кошки",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "crampons"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},
	{
		ID:       "ice_axes",
		Title:    "Ледорубы",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "ice_axes"},
		Level:    2,
		Order:    40,
		IsLeaf:   true,
	},
	{
		ID:       "mountain_other",
		Title:    "Другое",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "mountain_other"},
		Level:    2,
		Order:    50,
		IsLeaf:   true,
	},

	// --- Водное ---
	{
		ID:       "water",
		Title:    "Водное",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "water"},
		Level:    1,
		Order:    20,
		IsLeaf:   false,
	},
	{
		ID:       "watercraft",
		Title:    "Плав средства",
		ParentID: strPtr("water"),
		Path:     []string{"equipment", "water", "watercraft"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "water_gear",
		Title:    "Обмундирование",
		ParentID: strPtr("water"),
		Path:     []string{"equipment", "water", "water_gear"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "water_other",
		Title:    "Другое",
		ParentID: strPtr("water"),
		Path:     []string{"equipment", "water", "water_other"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},

	// --- Палатки ---
	{
		ID:       "shelters",
		Title:    "Палатки/тенты/шатры",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "shelters"},
		Level:    1,
		Order:    30,
		IsLeaf:   false,
	},
	{
		ID:       "tents",
		Title:    "Палатки",
		ParentID: strPtr("shelters"),
		Path:     []string{"equipment", "shelters", "tents"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "pavilions",
		Title:    "Шатры",
		ParentID: strPtr("shelters"),
		Path:     []string{"equipment", "shelters", "pavilions"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "tarps",
		Title:    "Тенты",
		ParentID: strPtr("shelters"),
		Path:     []string{"equipment", "shelters", "tarps"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},

	// --- Рюкзаки ---
	{
		ID:       "backpacks",
		Title:    "Рюкзаки",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "backpacks"},
		Level:    1,
		Order:    40,
		IsLeaf:   false,
	},
	{
		ID:       "backpacks_normal",
		Title:    "Нормальные",
		ParentID: strPtr("backpacks"),
		Path:     []string{"equipment", "backpacks", "backpacks_normal"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "backpacks_old",
		Title:    "Старые",
		ParentID: strPtr("backpacks"),
		Path:     []string{"equipment", "backpacks", "backpacks_old"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},

	{
		ID:       "sleeping_bags",
		Title:    "Спальные мешки",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "sleeping_bags"},
		Level:    1,
		Order:    50,
		IsLeaf:   true,
	},
	{
		ID:       "cookware",
		Title:    "Посуда",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "cookware"},
		Level:    1,
		Order:    60,
		IsLeaf:   true,
	},
	{
		ID:       "axes_saws",
		Title:    "Топоры/пилы",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "axes_saws"},
		Level:    1,
		Order:    70,
		IsLeaf:   true,
	},
	{
		ID:       "campfire",
		Title:    "Костровое",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "campfire"},
		Level:    1,
		Order:    80,
		IsLeaf:   true,
	},

	// --- Лыжное ---
	{
		ID:       "ski",
		Title:    "Лыжное",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "ski"},
		Level:    1,
		Order:    90,
		IsLeaf:   false,
	},
	{
		ID:       "skis",
		Title:    "Лыжи",
		ParentID: strPtr("ski"),
		Path:     []string{"equipment", "ski", "skis"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "snow_tools",
		Title:    "Снежный инструмент",
		ParentID: strPtr("ski"),
		Path:     []string{"equipment", "ski", "snow_tools"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "ski_stoves",
		Title:    "Печки",
		ParentID: strPtr("ski"),
		Path:     []string{"equipment", "ski", "ski_stoves"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},

	// ===== Инвентарь =====
	{
		ID:       "inventory",
		Title:    "Инвентарь",
		ParentID: strPtr(models.RootParentID),
		Path:     []string{"inventory"},
		Level:    0,
		Order:    20,
		IsLeaf:   false,
	},
	{
		ID:       "furniture",
		Title:    "Мебель",
		ParentID: strPtr("inventory"),
		Path:     []string{"inventory", "furniture"},
		Level:    1,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "generators",
		Title:    "Генераторы",
		ParentID: strPtr("inventory"),
		Path:     []string{"inventory", "generators"},
		Level:    1,
		Order:    20,
		IsLeaf:   true,
	},
}
