package seed

import (
	"ekapterka/internal/models"
)

func strPtr(s string) *string {
	return &s
}

var Categories = []models.Category{
	// ===== Снаряжение =====
	{
		ID:       "equipment",
		Title:    "Снаряжение",
		ParentID: nil,
		Path:     []string{"equipment"},
		Level:    0,
		Order:    10,
		IsLeaf:   false,
	},

	// --- Горное ---
	{
		ID:       "mountain",
		Title:    "Горное",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "mountain"},
		Level:    1,
		Order:    10,
		IsLeaf:   false,
	},

	// Железо
	{
		ID:       "hardware",
		Title:    "Железо",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "hardware"},
		Level:    2,
		Order:    10,
		IsLeaf:   false,
	},
	{
		ID:       "carabiners",
		Title:    "Карабины",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "carabiners"},
		Level:    3,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "figure_eights",
		Title:    "Восьмерки",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "figure_eights"},
		Level:    3,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "ascenders",
		Title:    "Жумары",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "ascenders"},
		Level:    3,
		Order:    30,
		IsLeaf:   true,
	},
	{
		ID:       "hardware_other",
		Title:    "Другое",
		ParentID: strPtr("hardware"),
		Path:     []string{"equipment", "mountain", "hardware", "hardware_other"},
		Level:    3,
		Order:    40,
		IsLeaf:   true,
	},

	{
		ID:       "ropes",
		Title:    "Веревки",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "ropes"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "crampons",
		Title:    "Кошки",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "crampons"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},
	{
		ID:       "ice_axes",
		Title:    "Ледорубы",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "ice_axes"},
		Level:    2,
		Order:    40,
		IsLeaf:   true,
	},
	{
		ID:       "mountain_other",
		Title:    "Другое",
		ParentID: strPtr("mountain"),
		Path:     []string{"equipment", "mountain", "mountain_other"},
		Level:    2,
		Order:    50,
		IsLeaf:   true,
	},

	// --- Одежда / обувь ---
	{
		ID:       "clothing_footwear",
		Title:    "Одежда/обувь",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "clothing_footwear"},
		Level:    1,
		Order:    20,
		IsLeaf:   false,
	},
	{
		ID:       "clothing",
		Title:    "Одежда",
		ParentID: strPtr("clothing_footwear"),
		Path:     []string{"equipment", "clothing_footwear", "clothing"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "footwear",
		Title:    "Обувь",
		ParentID: strPtr("clothing_footwear"),
		Path:     []string{"equipment", "clothing_footwear", "footwear"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},

	// --- Водное ---
	{
		ID:       "water",
		Title:    "Водное",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "water"},
		Level:    1,
		Order:    30,
		IsLeaf:   false,
	},
	{
		ID:       "watercraft",
		Title:    "Плав средства",
		ParentID: strPtr("water"),
		Path:     []string{"equipment", "water", "watercraft"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "water_gear",
		Title:    "Обмундирование",
		ParentID: strPtr("water"),
		Path:     []string{"equipment", "water", "water_gear"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "water_other",
		Title:    "Другое",
		ParentID: strPtr("water"),
		Path:     []string{"equipment", "water", "water_other"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},

	// --- Палатки / тенты / шатры ---
	{
		ID:       "shelters",
		Title:    "Палатки/тенты/шатры",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "shelters"},
		Level:    1,
		Order:    40,
		IsLeaf:   false,
	},
	{
		ID:       "tents",
		Title:    "Палатки",
		ParentID: strPtr("shelters"),
		Path:     []string{"equipment", "shelters", "tents"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "pavilions",
		Title:    "Шатры",
		ParentID: strPtr("shelters"),
		Path:     []string{"equipment", "shelters", "pavilions"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "tarps",
		Title:    "Тенты",
		ParentID: strPtr("shelters"),
		Path:     []string{"equipment", "shelters", "tarps"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},

	// --- Рюкзаки ---
	{
		ID:       "backpacks",
		Title:    "Рюкзаки",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "backpacks"},
		Level:    1,
		Order:    50,
		IsLeaf:   false,
	},
	{
		ID:       "backpacks_40",
		Title:    "до 40 литров",
		ParentID: strPtr("backpacks"),
		Path:     []string{"equipment", "backpacks", "backpacks_40"},
		Level:    2,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "backpacks_40_70",
		Title:    "40 - 70",
		ParentID: strPtr("backpacks"),
		Path:     []string{"equipment", "backpacks", "backpacks_40_70"},
		Level:    2,
		Order:    20,
		IsLeaf:   true,
	},
	{
		ID:       "backpacks_70_100",
		Title:    "70 - 100 литров",
		ParentID: strPtr("backpacks"),
		Path:     []string{"equipment", "backpacks", "backpacks_70_100"},
		Level:    2,
		Order:    30,
		IsLeaf:   true,
	},

	{
		ID:       "sleeping_bags",
		Title:    "Спальные мешки",
		ParentID: strPtr("equipment"),
		Path:     []string{"equipment", "sleeping_bags"},
		Level:    1,
		Order:    60,
		IsLeaf:   true,
	},

	// ===== Стройматериалы =====
	{
		ID:       "building_materials",
		Title:    "Стройматериалы",
		ParentID: nil,
		Path:     []string{"building_materials"},
		Level:    0,
		Order:    20,
		IsLeaf:   false,
	},
	{
		ID:       "boards",
		Title:    "Доски",
		ParentID: strPtr("building_materials"),
		Path:     []string{"building_materials", "boards"},
		Level:    1,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "cement",
		Title:    "Цемент",
		ParentID: strPtr("building_materials"),
		Path:     []string{"building_materials", "cement"},
		Level:    1,
		Order:    20,
		IsLeaf:   true,
	},

	// ===== Инвентарь =====
	{
		ID:       "inventory",
		Title:    "Инвентарь",
		ParentID: nil,
		Path:     []string{"inventory"},
		Level:    0,
		Order:    30,
		IsLeaf:   false,
	},
	{
		ID:       "furniture",
		Title:    "Мебель",
		ParentID: strPtr("inventory"),
		Path:     []string{"inventory", "furniture"},
		Level:    1,
		Order:    10,
		IsLeaf:   true,
	},
	{
		ID:       "generators",
		Title:    "Генераторы",
		ParentID: strPtr("inventory"),
		Path:     []string{"inventory", "generators"},
		Level:    1,
		Order:    20,
		IsLeaf:   true,
	},
}
